# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f68ce17e41669bd659c8b7018db90dd1b5e20c49e77d29ee297d86e5e226e04d76a698f94ed7a483abab9d85c07527b68e6ec8cdd4efc491c47ccb726a5e665

test:
  secret_key_base: f7740cbeb445a9cebf223c7c797a794a33a9f4f31283d7cd723cc4998257199826226d75ebae9e19c61553fb0fc9755eaa5bd3ee1de3464b5441cb1542ad29ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
